# Generated by Django 3.2.6 on 2021-08-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceUsersApp', '0002_auto_20210819_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuser',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ecommerceuser',
            name='address',
            field=models.CharField(default='Bogotá, Colombia', max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='ecommerceuser',
            name='telephone',
            field=models.IntegerField(default=0, verbose_name='Telephone'),
        ),
    ]
